#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

ERROR=0

echo "\e[10;34m"
echo "[hook] pre-commit: Building native-release"
echo "\e[0m"
if ! cmake --workflow --preset native-release; then
    ERROR=1
fi

echo "\e[10;34m"
echo "[hook] pre-commit: Building stm32f411re-minsizerel"
echo "\e[0m"
if ! cmake --workflow --preset stm32f411re-minsizerel; then
    ERROR=1
fi

echo "\e[10;34m"
if [ $ERROR -ne 0 ]; then
    echo "[hook] pre-commit: \e[10;31mSome tests failed\e[10;34m"
else
    echo "[hook] pre-commit: \e[10;32mAll tests passed\e[10;34m"
fi
echo "\e[0m"

exit $ERROR
