branches:
  only:
  - master
  - ci/travis 

sudo: required

os:
  - linux

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - lcov

before_script:
  # init coverage to 0 (optional)
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cd ${TRAVIS_BUILD_DIR} && lcov --directory . --zerocounters ; fi
  - mkdir build
  - cd build
  - cmake ..

script:
  - make && make test
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
