name: Build & Tests

on: [push, pull_request]

jobs:

  build:

    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-latest
            name: Ubuntu GCC
            artifact: ubuntu-gcc
            compiler: gcc
          - os: ubuntu-latest
            name: Ubuntu Clang
            artifact: ubuntu-clang
            compiler: clang
          - os: macos-latest
            name: MacOS Clang
            artifact: macos-clang
            compiler: clang
          - os: windows-latest
            name: Windows MinGW
            artifact: windows-mingw
            compiler: gcc
            extra_cmake_args: -G "MSYS Makefiles"
          - os: ubuntu-latest
            name: STM32 GCC
            artifact: stm32-gcc
            compiler: gcc
            extra_cmake_args: -DCMAKE_TOOLCHAIN_FILE=cmake/Toolchains/Stm32Gcc.cmake -DSTM32_TOOLCHAIN_PATH=/tmp/gcc-arm-none-eabi -DNSH_PLATFORM_NAME=Stm32NucleoF411RE
        build_type: [Release, Debug]

    name: ${{ matrix.config.name }} - ${{ matrix.build_type }}
    runs-on: ${{ matrix.config.os }}

    steps:
      
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install cmake

      - name: Install arm-none-eabi-gcc
        if: ${{ matrix.config.name == 'STM32 GCC' }}
        uses: fiam/arm-none-eabi-gcc@v1
        with:
          release: "9-2019-q4"
          directory: /tmp/gcc-arm-none-eabi

      - name: Configure
        env:
          CC: ${{ matrix.config.compiler }}
          CXX: ${{ matrix.config.compiler }}
        run: |
          cmake ${{ matrix.config.extra_cmake_args }} -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
      
      - name: Build
        run: |
          cmake --build build --config ${{ matrix.build_type }}
      
      - name: Run tests
        working-directory: build
        run: ctest

      - name: Install Strip
        run: |
          cmake --install build --prefix instdir --strip
      
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          path: ./instdir
          name: ${{ matrix.config.artifact }}-${{ matrix.build_type }}
